### ISSUE TITLE
Light theme equivalent?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Codecademy/codecademy-syntax-theme-vscode#1]
Is there any chance we could have a light theme? I want to be able to rep Codecademy when there's too much of a glare on my laptop for a dark theme. 😉

**Comment by jonsamp** [comment]
Currently we have two Codecademy themes. One in the web app (which is original colors with a recently new background color), and another theme in the mobile app.

I don't know the light colors for our original theme, but we are moving to these colors (defined [here](http://styleguide.codecademy.com/storybook/?selectedKind=Visuals%2FColors&selectedStory=Gamut%20%28New%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)):

```js
const ideDark = {
  blue: colors.blue[400],
  red: colors.red[400],
  mint: colors.mint[400],
  yellow: colors.yellow[400],
  pink: colors.pink[400],
  deepPurple: colors.deepPurple[200],
  beige: colors.beige,
  white: colors.white,
};

const ideLight = {
  red: colors.red[700],
  pink: colors.pink[800],
  mint: colors.mint[800],
  darkBlue: colors.blue[900],
  blue: colors.blue[500],
  yellow: colors.yellow[900],
  deepPurple: colors.deepPurple[600],
};
```

Perhaps we can make another repo with the light theme.

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues in repos that haven't had updates in a few years. Cheers!
